export enum ActionTypes {
  ADD_PRODUCTS = 'ADD_PRODUCTS',
  SEND_PRODUCT_TO_CART = 'SEND_PRODUCT_TO_CART',
  REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART',
  EMPTY_CART = 'EMPTY_CART',
  SET_USER = 'SET_USER',
  GET_USER_CART = 'GET_USER_CART',
}
